import Navbar from "./Navbar";
import Hero from "./Hero";
import GetStarted from "./GetStarted";
import Stats from "./Stats";
import Business from "./Business";
import Button from "./Button";
import Billing from "./Billing";
import CardDeal from "./CardDeal";
import Testimonials from "./Testimonials";
import FeedbackCard from "./FeedbackCard";
import Clients from "./Clients";
import CTA from "./CTA";
import Footer from "./Footer";
export { Navbar, Hero, GetStarted, Stats, Business, Button, Footer, Billing, CardDeal, Testimonials, FeedbackCard, Clients, CTA};
